### ISSUE TITLE
Cost for underutilised resources

### ISSUE THREAD

**Issue by sankeyraut** [turbot/steampipe-mod-aws-thrifty#100]
**Is your feature request related to a problem? Please describe.**
The thrify mod shows list of underutilised resources which is a good starting point. However it will be good if we can show $ cost associated with the underutilised resource so that we can plan and prioritize action. 

**Describe the solution you'd like**
Along with the resource list, please include the ondemand cost of the resource. 

**Describe alternatives you've considered**
Recently a new table has been added to query the cost of the resource. (https://github.com/turbot/steampipe-plugin-aws/issues/632) called as aws_pricing_product. Alternative is to join the query used in thrify mod with this table to come up with the cost manually. 

**Additional context**
This will help create actionable dashboards with $ numbers and can help service owner set the priority for maximum cost savings.

**Comment by misraved** [comment]
Thanks @sankeyraut for raising this request. We have actually been looking to update our thrifty controls with the addition of pricing value. As you mentioned, this would definitely help us in creating actionable dashboards.

Evaluating the cost per resource is definitely a bottleneck. We are still trying to develop an optimized design for our pricing tables as mentioned in the issue you created - https://github.com/turbot/steampipe-plugin-aws/issues/632.

Do you have any ideas/example queries that would help us evaluate the cost manually?
