### ISSUE TITLE
Why the NAT gateway which is actually being used comes under 'Unused NAT gateways should be deleted'

### ISSUE THREAD

**Issue by Niba-nazar** [turbot/steampipe-mod-aws-thrifty#111]
Why the NAT gateway which is actually in use comes under 'Unused NAT gateways should be deleted '

![image](https://user-images.githubusercontent.com/114569256/201604485-36e77c3f-19f6-4479-9978-ec39725d01ba.png)

**Comment by Niba-nazar** [comment]
Why the NAT gateway which is actually in use comes under 'Unused NAT gateways should be deleted '

![image](https://user-images.githubusercontent.com/114569256/201638987-a47b848d-d614-4886-900b-768eb5520c1e.png)


2days before the result was like the above pic, now it seems working:

image

**Comment by misraved** [comment]
Sorry for the glitch @Niba-nazar. Glad to see that you are unblocked 👍 .

The underlying query behind this control is https://github.com/turbot/steampipe-mod-aws-thrifty/blob/main/query/vpc/vpc_nat_gateway_unused.sql.

This looks at the following parameters before deeming a particular NAT Gateway unused:
- NAT Gateway state (`state` column in `aws_vpc_nat_gateway` table)
- Instance state
- Subnet ID attached to the instance

Is it possible that one of the above conditions was not met when the control was executed?
