### ISSUE TITLE
Transit Gateway Data Processing Charges

### ISSUE THREAD

**Issue by rbracewell** [turbot/steampipe-mod-aws-thrifty#123]
When you centralize NAT gateway using Transit Gateway, you pay an extra Transit Gateway data processing charge — compared to the decentralized approach of running a NAT gateway in every VPC. In some edge cases when you send huge amounts of data through NAT gateway from a VPC, keeping the NAT local in the VPC to avoid the Transit Gateway data processing charge might be a more cost-effective option.

Refer to AWS [whitepaper](https://docs.aws.amazon.com/whitepapers/latest/building-scalable-secure-multi-vpc-network-infrastructure/centralized-egress-to-internet.html).

It would be nice to surface a control to track this if possible.

**Comment by rbracewell** [comment]
Havent looked at ways to surface this yet was hoping tools like Steampipe and this mod had such a control.

**Comment by bigdatasourav** [comment]
Hey @rbracewell, sorry for the delayed response.

I have checked various docs and API responses of aws_ec2_transit_* and other vpc_* tables but could not find a way to map or track the above information. Please help us with your insights and findings if you have any.

**Comment by bigdatasourav** [comment]
Hey @rbracewell, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
