### ISSUE TITLE
Control: Old EBS snapshots should be deleted if not required

### ISSUE THREAD

**Issue by Musseri10** [turbot/steampipe-mod-aws-thrifty#132]
Hi,

I looked at the Old EBS snapshots should be deleted if not required checks and saw that the SQL query works on the table aws_secretsmanager_secret. I think there is a mistake there. Can you take a look?

**Comment by misraved** [comment]
Welcome to Steampipe @Musseri10 and thanks for raising this bug.

We have already fixed it in https://github.com/turbot/steampipe-mod-aws-thrifty/commit/973c7d7acad940e3e63091b3a297cd31e6fd1ddb

This bug fix will be released by EOD 👍.

**Comment by misraved** [comment]
@Musseri10 the fix is now available in the `v0.21` mod version 👍.

Thanks once again for spotting the bug.
