### ISSUE TITLE
Graviton processors cheaper (and more performant) than x86

### ISSUE THREAD

**Issue by joscheuerer** [turbot/steampipe-mod-aws-thrifty#142]
**Is your feature request related to a problem? Please describe.**
It has shown that Graviton2 and graviton3 processors are more performant and cheaper than equivalent x86 processors

**Describe the solution you'd like**
Implement findings for non graviton processors and suggest graviton2 or 3 instead.
Should be suggested for Linux, Ubuntu, ECS, EKS, k8s, RDS, 
 - (not for windows machines)

**Describe alternatives you've considered**
None

**Additional context**
Here are some links to comparisons: 
- https://dzone.com/articles/everything-you-need-to-know-about-aws-graviton2 
- https://dev.to/leading-edje/faster-cheaper-aws-graviton-2-2b0c

**Comment by rajlearner17** [comment]
@joscheuerer Thanks for using Steampipe, and I appreciate raising this requirement. 

We will start looking into it; any PR is welcome 👍 from the community

Cheers!
