### ISSUE TITLE
Getting `ERROR: failed to encode args[0]: unable to encode 90 into text format for text` for control ebs_snapshot_max_age

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-mod-aws-thrifty#145]
**Describe the bug**
Getting below error for control ebs_snapshot_max_age
`ERROR: failed to encode args[0]: unable to encode 90 into text format for text (OID 25): cannot find encode plan`

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-mod-aws-thrifty/pull/147
