### ISSUE TITLE
Getting `ERROR: column reference "account_id" is ambiguous` error for control `multiple_global_trails`

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-mod-aws-thrifty#146]
**Describe the bug**
Getting below error for control `multiple_global_trails`
`ERROR: column reference "account_id" is ambiguous (SQLSTATE 42702)`

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-mod-aws-thrifty/pull/147
