### ISSUE TITLE
Unused log stream finding should be removed from the checks

### ISSUE THREAD

**Issue by joscheuerer** [turbot/steampipe-mod-aws-thrifty#159]
**Is your feature request related to a problem? Please describe.**
The finding under 'cloudwatch' called 'Unused log streams should be removed if not required' is not really a cost finding, because removing it, does not reduce the cost. It is at most a best practise for Cloud accounts.

Since it has a lot of findings and does not add to the savings, it is reducing the confidence into steampipe rules. 

Can you remove this finding ?!

**Describe the solution you'd like**
Removing the check.

**Describe alternatives you've considered**
Creating a fork and adapting myself, but it should be done in the steampipe directly.

**Additional context**

**Comment by cbruno10** [comment]
Hey @joscheuerer , from what I could find about [CloudWatch's pricing](https://aws.amazon.com/cloudwatch/pricing/), it seems like there's a cost of ~$0.03/GB for log storage in log groups. I haven't checked out my CW log billing in a bit, but I believe if log streams are cleaned up/deleted, then the overall storage cost of the log group could be reduced.

Does this seem consistent with what you know about CW's pricing models? And thanks for opening up this issue!

**Comment by joscheuerer** [comment]
Hey @cbruno10, The streams themself are not charged (https://aws.amazon.com/blogs/mt/delete-empty-cloudwatch-log-streams/) so I would not see it as a cost policy but it would be at max a best practise. The storage of the logs and log group retention is a cost issue but this is already captured here: https://hub.steampipe.io/mods/turbot/aws_thrifty/controls/control.cw_log_group_retention?context=benchmark.cloudwatch
