### ISSUE TITLE
Update control "low_iops_ebs_volumes" to convert io1 and io2 volumes with less than 16,000 IOPS to GP3

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-mod-aws-thrifty#166]
**Describe the bug**
Update control "low_iops_ebs_volumes" to convert io1 and io2 volumes with less than 16,000 IOPS to GP3

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-mod-aws-thrifty/pull/167
