### ISSUE TITLE
AWS extended support pricing for old RDS 

### ISSUE THREAD

**Issue by joscheuerer** [turbot/steampipe-mod-aws-thrifty#170]
**Is your feature request related to a problem? Please describe.**
AWS increases pricing for RDS when using old mysql or postgreSQL DBs.

**Describe the solution you'd like**
Find the resources with old RDS in the AWS account and suggest an upgrade.

**Describe alternatives you've considered**
No real laternative .... finding the RDS yourself

**Additional context**
Here the issue is discribed: https://medium.com/@totoshko88/prevent-automatic-rds-extended-support-charges-for-unsupported-versions-deed0ba3f51f

**Comment by joscheuerer** [comment]
Hello @khushboo9024 , 

do you have any questions regarding this issue, please let me know. 

Can you give me the status on this or when you are expecting to have this done? 

Best 
Jo

**Comment by khushboo9024** [comment]
Hi @joscheuerer, sorry for being silent on this. We will add this to our priority list and let you know if we have any questions about it. We will try to release it as soon as possible.
Thanks!!

**Comment by joscheuerer** [comment]
Thank you for the update!

Am Mi., 13. März 2024 um 08:12 Uhr schrieb Khushboo <
***@***.***>:

**Comment by khushboo9024** [comment]
Hi [joscheuerer](https://github.com/joscheuerer), we have added a control `rds_mysql_postresql_db_no_unsupported_version` for this and pushed the changes to the [branch](https://github.com/turbot/steampipe-mod-aws-thrifty/tree/issue-170). Can you check and let us know if it's good from your side? Thanks!"

**Comment by joscheuerer** [comment]
Hi Khushboo,

one question regarding the versioning. Is the mysql version that is checked
via the API related to the 'community version' (5.7) or the Aurora mysql
version (2)?
This table shows both:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.VersionPolicy.html#Aurora.VersionPolicy.MajorVersions


Not sure what you get back from the API , but were you able to test this?

All the best
Jo

Am Di., 19. März 2024 um 08:13 Uhr schrieb Khushboo <
***@***.***>:

**Comment by khushboo9024** [comment]
Hi [joscheuerer](https://github.com/joscheuerer), we've conducted tests on both the MySQL Community Edition and the Aurora MySQL database instance. The new query verifies both the `MySQL Community Edition (version 5.7) and the Aurora MySQL version (2).`
Here are the API responses indicating the versions for both database instance types:
 - MySql community version' (5.7.44 ) - `5.7.44`
 - Aurora MySql version (2) - `5.7.mysql_aurora.2.11.4`
 
 Please let us know If any concerns.
 Thanks!!

**Comment by joscheuerer** [comment]
Thank you for the update.
That sounds all great.

Please let me know once it is merged to main.

All the best
Jo

Am Mi., 27. März 2024 um 08:22 Uhr schrieb Khushboo <
***@***.***>:
