### ISSUE TITLE
Add control that checks VPC flow log data for unused resources

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-mod-aws-thrifty#24]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to look for unused/underutilized resources by looking at VPC flow log data and checking which resources have no traffic in/out to them.

**Describe the solution you'd like**
Add a control that checks VPC flow log data and alarms on resources with no inbound/outbound traffic.

**Describe alternatives you've considered**

**Additional context**

**Comment by alves-alisson** [comment]
This feature has implemented?
