### ISSUE TITLE
quoted param is not used by control

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-mod-aws-thrifty#68]
In `old_ebs_snapshots.sql` the param is quoted:

```
when start_time > current_timestamp - interval '$1 days' then 'ok'
```

As such it's just a string, so the query is incorrect.

per @johnsmyth, this variant works:

```
when start_time > current_timestamp - ($1 || ' days')::interval then 'ok'
```

We should probably search for this pattern across the corpus, a quick spot-check found this in gcp-thrifty: 

```
current_date - interval '$1' day
```

**Comment by misraved** [comment]
Thanks @judell for raising the issue.

Will look to get the fix out as soon as possible 👍

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-mod-aws-thrifty/pull/69
